var DEFAULT_LAYOUT = {
    "version":  "1.0",
    "appName":  "Primavera Universal Planner",
    "exportedAt":  "2026-07-09T18:14:50.846Z",
    "terrain":  {
                    "w":  50,
                    "h":  60
                },
    "elements":  [
                     {
                         "id":  "el_1783618755385_1783144606997",
                         "type":  "pool",
                         "category":  "estructuras",
                         "name":  "Alberca",
                         "x":  45,
                         "y":  6.9,
                         "w":  11.7,
                         "h":  7.7,
                         "rotation":  89,
                         "color":  "#0369a1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "estructuras",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783618879603_1783144606998",
                         "type":  "parking",
                         "category":  "estructuras",
                         "name":  "Estacionamiento",
                         "x":  10.9,
                         "y":  5.1000000000000005,
                         "w":  21.9,
                         "h":  8.7,
                         "rotation":  0,
                         "color":  "#374151",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "estructuras",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783618937001_1783144606999",
                         "type":  "salon",
                         "category":  "estructuras",
                         "name":  "SalÃ³n Techado",
                         "x":  28.6,
                         "y":  5.300000000000001,
                         "w":  13.3,
                         "h":  8.9,
                         "rotation":  0,
                         "color":  "#1e293b",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "estructuras",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        },
                         "salonType":  "sin_muros"
                     },
                     {
                         "id":  "el_1783619131407_1783144607000",
                         "type":  "red_carpet",
                         "category":  "entretenimiento",
                         "name":  "Alfombra Roja",
                         "x":  8.6,
                         "y":  18.400000000000002,
                         "w":  2.8,
                         "h":  12.8,
                         "rotation":  45,
                         "color":  "#dc2626",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "entretenimiento",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619179283_1783144607001",
                         "type":  "photobooth_inflatable",
                         "category":  "entretenimiento",
                         "name":  "Cabina Inflable",
                         "x":  28.1,
                         "y":  19.200000000000003,
                         "w":  7,
                         "h":  6.4,
                         "rotation":  0,
                         "color":  "#0369a1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "entretenimiento",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619240085_1783144607002",
                         "type":  "sparklers",
                         "category":  "entretenimiento",
                         "name":  "Chisperos",
                         "x":  7.6000000000000005,
                         "y":  25,
                         "w":  2.1,
                         "h":  0.5,
                         "rotation":  0,
                         "color":  "#f97316",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "entretenimiento",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619268237_1783144607003",
                         "type":  "sparklers",
                         "category":  "entretenimiento",
                         "name":  "Chisperos",
                         "x":  14.8,
                         "y":  16.6,
                         "w":  2.1,
                         "h":  0.5,
                         "rotation":  0,
                         "color":  "#f97316",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "entretenimiento",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619317207_1783144607004",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  38.1,
                         "y":  3.2,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619410057_1783144607005",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  38.1,
                         "y":  7.9,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619413949_1783144607006",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  38,
                         "y":  12,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619416753_1783144607007",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  38,
                         "y":  16.2,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619419121_1783144607008",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  38,
                         "y":  20.700000000000003,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619422391_1783144607009",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  38.1,
                         "y":  24.5,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619484841_1783144607010",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  37.9,
                         "y":  28.8,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619495929_1783144607011",
                         "type":  "arch_decor",
                         "category":  "decoracion",
                         "name":  "Arco Estructural/SalÃ³n",
                         "x":  37.7,
                         "y":  33.1,
                         "w":  2.5,
                         "h":  3,
                         "rotation":  91,
                         "color":  "#cbd5e1",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619536421_1783144607012",
                         "type":  "salon",
                         "category":  "estructuras",
                         "name":  "SalÃ³n Techado",
                         "x":  16.1,
                         "y":  49.1,
                         "w":  30.7,
                         "h":  20.5,
                         "rotation":  0,
                         "color":  "#1e293b",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "estructuras",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        },
                         "salonType":  "sin_muros"
                     },
                     {
                         "id":  "el_1783619636341_1783144607013",
                         "type":  "kitchen",
                         "category":  "estructuras",
                         "name":  "Ãrea de Cocina",
                         "x":  37.2,
                         "y":  54,
                         "w":  10.6,
                         "h":  10.6,
                         "rotation":  0,
                         "color":  "#78350f",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "estructuras",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  10,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619716845_1783144607014",
                         "type":  "door_main",
                         "category":  "accesos",
                         "name":  "Entrada Principal",
                         "x":  7.6000000000000005,
                         "y":  0.2,
                         "w":  6.5,
                         "h":  1.3,
                         "rotation":  0,
                         "color":  "#10b981",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "accesos",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619798961_1783144607015",
                         "type":  "bar_area",
                         "category":  "estructuras",
                         "name":  "Ãrea de Barra",
                         "x":  37.1,
                         "y":  43.300000000000004,
                         "w":  10.9,
                         "h":  9.6,
                         "rotation":  0,
                         "color":  "#92400e",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "estructuras",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783619888161_1783144607016",
                         "type":  "table_marble_square",
                         "category":  "mobiliario",
                         "name":  "Mesa MÃ¡rmol Cuadrada",
                         "x":  6.1000000000000005,
                         "y":  54.400000000000006,
                         "w":  2.6,
                         "h":  5.4,
                         "rotation":  0,
                         "color":  "#cbd5e1",
                         "chairs":  10,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "mobiliario",
                         "mesaConfig":  {
                                            "mesaNum":  20,
                                            "capacidadMax":  null,
                                            "mantelColor":  "sin_mantel",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620008932_1783144607017",
                         "type":  "table_marble_square",
                         "category":  "mobiliario",
                         "name":  "Mesa MÃ¡rmol Cuadrada",
                         "x":  15.700000000000001,
                         "y":  54.300000000000004,
                         "w":  2.6,
                         "h":  5.4,
                         "rotation":  0,
                         "color":  "#cbd5e1",
                         "chairs":  10,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "mobiliario",
                         "mesaConfig":  {
                                            "mesaNum":  21,
                                            "capacidadMax":  null,
                                            "mantelColor":  "sin_mantel",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620020049_1783144607018",
                         "type":  "table_marble_square",
                         "category":  "mobiliario",
                         "name":  "Mesa MÃ¡rmol Cuadrada",
                         "x":  24.700000000000003,
                         "y":  54.2,
                         "w":  2.6,
                         "h":  5.4,
                         "rotation":  0,
                         "color":  "#cbd5e1",
                         "chairs":  10,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "mobiliario",
                         "mesaConfig":  {
                                            "mesaNum":  22,
                                            "capacidadMax":  null,
                                            "mantelColor":  "sin_mantel",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620029315_1783144607019",
                         "type":  "table_marble_square",
                         "category":  "mobiliario",
                         "name":  "Mesa MÃ¡rmol Cuadrada",
                         "x":  24.700000000000003,
                         "y":  44.7,
                         "w":  2.6,
                         "h":  5.4,
                         "rotation":  0,
                         "color":  "#cbd5e1",
                         "chairs":  10,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "mobiliario",
                         "mesaConfig":  {
                                            "mesaNum":  23,
                                            "capacidadMax":  null,
                                            "mantelColor":  "sin_mantel",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620204793_1783144607020",
                         "type":  "dj_booth",
                         "category":  "entretenimiento",
                         "name":  "Cabina de DJ",
                         "x":  3.2,
                         "y":  44.6,
                         "w":  5.3,
                         "h":  2.3,
                         "rotation":  269,
                         "color":  "#0d0c1d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "entretenimiento",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620346811_1783144607021",
                         "type":  "door_single",
                         "category":  "accesos",
                         "name":  "Puerta Sencilla",
                         "x":  50,
                         "y":  20.1,
                         "w":  5.1,
                         "h":  2.4,
                         "rotation":  90,
                         "color":  "#10b981",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "accesos",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620654367_1783144607022",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  1.8,
                         "y":  35.6,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620680443_1783144607023",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  2.2,
                         "y":  29.200000000000003,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620693696_1783144607024",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  1.8,
                         "y":  13.3,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620704891_1783144607025",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  7.800000000000001,
                         "y":  12.700000000000001,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620716619_1783144607026",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  28.5,
                         "y":  11.9,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620735127_1783144607027",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  33.5,
                         "y":  32.9,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620742042_1783144607028",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  47.300000000000004,
                         "y":  26.700000000000003,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     },
                     {
                         "id":  "el_1783620750689_1783144607029",
                         "type":  "tree_decor",
                         "category":  "decoracion",
                         "name":  "Ãrbol Decorativo",
                         "x":  47.300000000000004,
                         "y":  32.1,
                         "w":  3,
                         "h":  2.4,
                         "rotation":  0,
                         "color":  "#15803d",
                         "chairs":  0,
                         "editable":  true,
                         "removable":  true,
                         "layer":  "decoracion",
                         "mesaConfig":  {
                                            "mesaNum":  0,
                                            "capacidadMax":  null,
                                            "mantelColor":  "blanco",
                                            "caminoColor":  "dorado",
                                            "caminoAcomodo":  "diagonal",
                                            "servilletaColorCorazon":  "dorado",
                                            "servilletaColorCorbata":  "champagne",
                                            "servilletaColorOtros":  "blanco",
                                            "servilletaDoblez":  [
                                                                     "corazon",
                                                                     "corbata"
                                                                 ],
                                            "cubiertos":  "plateado",
                                            "platoBase":  "ninguno",
                                            "platoTrinche":  "redondo_blanco",
                                            "cristal":  "cubero",
                                            "copasColor":  "transparente",
                                            "cristal2":  "ninguno",
                                            "copasColor2":  "transparente",
                                            "tipoSilla":  "tiffany",
                                            "menu":  "",
                                            "arregloFloralTipo":  "bajo",
                                            "arregloFloralAcomodo":  "diagonal",
                                            "ensambleTipo":  "angosto",
                                            "invitados":  [

                                                          ]
                                        }
                     }
                 ],
    "layers":  {
                   "estructuras":  true,
                   "techos":  false,
                   "accesos":  true,
                   "mobiliario":  true,
                   "entretenimiento":  true,
                   "decoracion":  true,
                   "proveedores":  true,
                   "flujo_invitados":  true,
                   "flujo_proveedores":  true,
                   "flujo_staff":  true
               }
};
