var DEFAULT_LAYOUT = {
  "version": "1.0",
  "appName": "Primavera Universal Planner",
  "exportedAt": "2026-06-24T20:56:05.446Z",
  "terrain": {
    "w": 50,
    "h": 60
  },
  "elements": [
    {
      "id": "el_1782328230247_1",
      "type": "terrain",
      "category": "estructuras",
      "name": "Terreno Base",
      "x": 25.200000000000003,
      "y": 29.900000000000002,
      "w": 50,
      "h": 60,
      "rotation": 0,
      "color": "#1a2744",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "bg",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782328234176_2",
      "type": "salon",
      "category": "estructuras",
      "name": "Salón Techado",
      "x": 31.200000000000003,
      "y": 18,
      "w": 33.9,
      "h": 35.1,
      "rotation": 0,
      "color": "#1e293b",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "estructuras",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782331899288_3",
      "type": "terrain",
      "category": "estructuras",
      "name": "Terreno Base",
      "x": 25.1,
      "y": 28.6,
      "w": 50,
      "h": 55.4,
      "rotation": 0,
      "color": "#1a2744",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "bg",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332070498_4",
      "type": "pool",
      "category": "estructuras",
      "name": "Alberca",
      "x": 7.1000000000000005,
      "y": 41.400000000000006,
      "w": 11.7,
      "h": 12.5,
      "rotation": 90,
      "color": "#0369a1",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "estructuras",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332356872_5",
      "type": "terrace",
      "category": "estructuras",
      "name": "Terraza",
      "x": 7.300000000000001,
      "y": 18,
      "w": 13.1,
      "h": 35,
      "rotation": 0,
      "color": "#1e3a5f",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "estructuras",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332557254_7",
      "type": "gate_large",
      "category": "accesos",
      "name": "Portón de Acceso",
      "x": 27.8,
      "y": 60,
      "w": 4.5,
      "h": 0.4,
      "rotation": 0,
      "color": "#334155",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "accesos",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332565358_8",
      "type": "bathroom",
      "category": "accesos",
      "name": "Baños",
      "x": 7.5,
      "y": 57,
      "w": 13.3,
      "h": 4.2,
      "rotation": 0,
      "color": "#0891b2",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "accesos",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332659588_9",
      "type": "kitchen",
      "category": "estructuras",
      "name": "Área de Cocina",
      "x": 41.6,
      "y": 55.7,
      "w": 15.5,
      "h": 7.9,
      "rotation": 0,
      "color": "#78350f",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "estructuras",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332733540_10",
      "type": "bar_area",
      "category": "estructuras",
      "name": "Área de Barra",
      "x": 7.300000000000001,
      "y": 2.7,
      "w": 8.6,
      "h": 4.1,
      "rotation": 0,
      "color": "#92400e",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "estructuras",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332781078_11",
      "type": "kids_area",
      "category": "estructuras",
      "name": "Área Infantil",
      "x": 43.7,
      "y": 39.7,
      "w": 9.9,
      "h": 7.1,
      "rotation": 0,
      "color": "#7c3aed",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "estructuras",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332819192_12",
      "type": "lobby_reception",
      "category": "estructuras",
      "name": "Lobby/Recepción",
      "x": 24.200000000000003,
      "y": 56.7,
      "w": 18.1,
      "h": 4.7,
      "rotation": 0,
      "color": "#374151",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "estructuras",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332851752_13",
      "type": "stairs",
      "category": "accesos",
      "name": "Escaleras",
      "x": 1.8,
      "y": 56.800000000000004,
      "w": 2,
      "h": 5.1,
      "rotation": 360,
      "color": "#64748b",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "accesos",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782332973416_14",
      "type": "table_honor_xv",
      "category": "mobiliario",
      "name": "Mesa Honor XV",
      "x": 31.4,
      "y": 2.7,
      "w": 14.1,
      "h": 3.5,
      "rotation": 0,
      "color": "#f472b6",
      "chairs": 10,
      "editable": true,
      "removable": true,
      "layer": "mobiliario",
      "mesaConfig": {
        "mesaNum": 14,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782333003464_15",
      "type": "giant_letters",
      "category": "entretenimiento",
      "name": "Letras Gigantes",
      "x": 6.1000000000000005,
      "y": 9.5,
      "w": 7.5,
      "h": 2.5,
      "rotation": 323,
      "color": "#f59e0b",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "entretenimiento",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782333031916_16",
      "type": "tree_decor",
      "category": "decoracion",
      "name": "Árbol Decorativo",
      "x": 32.6,
      "y": 41,
      "w": 1.5,
      "h": 7.5,
      "rotation": 0,
      "color": "#15803d",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "decoracion",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782333144880_17",
      "type": "photobooth_inflatable",
      "category": "entretenimiento",
      "name": "Cabina Inflable",
      "x": 6.9,
      "y": 27.700000000000003,
      "w": 3,
      "h": 3,
      "rotation": 0,
      "color": "#0369a1",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "entretenimiento",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782333151748_18",
      "type": "photobooth_360",
      "category": "entretenimiento",
      "name": "Cabina 360°",
      "x": 7,
      "y": 18.3,
      "w": 3,
      "h": 3,
      "rotation": 0,
      "color": "#1e3a8a",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "entretenimiento",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782333947644_19",
      "type": "dj_booth",
      "category": "entretenimiento",
      "name": "Cabina de DJ",
      "x": 44.2,
      "y": 3,
      "w": 7.2,
      "h": 1.7,
      "rotation": 25,
      "color": "#0d0c1d",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "entretenimiento",
      "mesaConfig": {
        "mesaNum": 0,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    },
    {
      "id": "el_1782334027164_20",
      "type": "table_imperial",
      "category": "mobiliario",
      "name": "Mesa Imperial",
      "x": 19.3,
      "y": 28,
      "w": 12.3,
      "h": 6,
      "rotation": 90,
      "color": "#5c3d2e",
      "chairs": 50,
      "tablones": 5,
      "editable": true,
      "removable": true,
      "layer": "mobiliario",
      "mesaConfig": {
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": "",
        "mesaNum": 20
      }
    },
    {
      "id": "el_1782334148512_21",
      "type": "table_imperial",
      "category": "mobiliario",
      "name": "Mesa Imperial",
      "x": 36.9,
      "y": 28.1,
      "w": 12.3,
      "h": 6,
      "rotation": 90,
      "color": "#5c3d2e",
      "chairs": 50,
      "tablones": 5,
      "editable": true,
      "removable": true,
      "layer": "mobiliario",
      "mesaConfig": {
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": "",
        "mesaNum": 21
      }
    },
    {
      "id": "el_1782334149150_22",
      "type": "table_imperial",
      "category": "mobiliario",
      "name": "Mesa Imperial",
      "x": 45.400000000000006,
      "y": 28.200000000000003,
      "w": 12.3,
      "h": 6,
      "rotation": 90,
      "color": "#5c3d2e",
      "chairs": 50,
      "tablones": 5,
      "editable": true,
      "removable": true,
      "layer": "mobiliario",
      "mesaConfig": {
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": "",
        "mesaNum": 22
      }
    },
    {
      "id": "el_1782334178156_23",
      "type": "table_imperial",
      "category": "mobiliario",
      "name": "Mesa Imperial",
      "x": 28.3,
      "y": 28.1,
      "w": 12.3,
      "h": 6,
      "rotation": 90,
      "color": "#5c3d2e",
      "chairs": 50,
      "tablones": 5,
      "editable": true,
      "removable": true,
      "layer": "mobiliario",
      "mesaConfig": {
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": "",
        "mesaNum": 23
      }
    },
    {
      "id": "el_1782334332716_24",
      "type": "table_cake",
      "category": "mobiliario",
      "name": "Mesa de Pastel",
      "x": 18,
      "y": 3.7,
      "w": 7.2,
      "h": 2.2,
      "rotation": 327,
      "color": "#f472b6",
      "chairs": 0,
      "editable": true,
      "removable": true,
      "layer": "mobiliario",
      "mesaConfig": {
        "mesaNum": 24,
        "mantelColor": "blanco",
        "caminoColor": "ninguno",
        "servilletaColor": "blanco",
        "servilletaDoblez": "loto",
        "cubiertos": "plateado",
        "platoBase": "ninguno",
        "platoTrinche": "redondo_blanco",
        "cristal": "standard",
        "copasColor": "transparente",
        "tipoSilla": "tiffany",
        "menu": ""
      }
    }
  ],
  "layers": {
    "estructuras": true,
    "techos": true,
    "accesos": true,
    "mobiliario": true,
    "entretenimiento": true,
    "decoracion": true,
    "proveedores": true,
    "flujo_invitados": true,
    "flujo_proveedores": true,
    "flujo_staff": true
  }
};